// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqbxgmgkhlqntrkwzojk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxYnhnbWdraGxxbnRya3d6b2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4Mzc4NzAsImV4cCI6MjA2MTQxMzg3MH0.lxUAUMem9QuZ2LMtHHS6tE8nR9NTJhfeZEnydgQ17Vs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);